version: '3'

services:
  n1:
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - ./data/n1:/var/lib/mysql
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_ROOT_HOST=%
        
  n2:
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - ./data/n2:/var/lib/mysql
    ports:
      - "3302:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_ROOT_HOST=%

  n3:
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - ./data/n3:/var/lib/mysql
    ports:
      - "3303:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_ROOT_HOST=%

  n4:
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=4","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - ./data/n4:/var/lib/mysql
    ports:
      - "3304:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_ROOT_HOST=%

  shell:
    image: mysql/mysql-server:8.0.12
    volumes:
      - ./scripts/clusterConf.sh:/docker-entrypoint-initdb.d/clusterConf.sh
    depends_on:
      - n1
      - n2
      - n3
      - n4
    environment:
      - MYSQL_USER=root
      - MYSQL_HOST=n1
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=pass123
  
  router:
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      - n1
      - n2
      - n3
      - n4
      - shell
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_HOST=n1
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=pass123
      - MYSQL_INNODB_NUM_MEMBERS=4